### ISSUE TITLE
Atualizar requisições do Front-End

### ISSUE THREAD

**Issue by MariaCHelena** [unb-mds/LicitaBSB-24.1#114]
**Descrição/Objetivo:**
Com a refatoração do backend, se tornou necessário atualizar a forma que o front-end está obtendo e filtrando os dados de licitação. Sendo assim, para essa issue, é preciso refatorar as requisições de licitações e filtragem de licitações no front end.

**Tarefas:**
- [x] Atualizar as requisições de licitações na landing page;
- [x] Atualizar as requisições de licitações na página de licitações;
- [ ] Atualizar a paginação de licitações;
- [ ] Atualizar os filtros de licitações.

**Critérios de aceitação:**
- [ ] Todas as requisições deverão estar na pasta de "services".

**Comment by MariaCHelena** [comment]
@m4rllon e @nateejpg, sempre coloquem os códigos das chamadas da API dentro da pasta de 'services'. E ao chamar a API, chama a contante 'api', que tá dentro do arquivo api.js, na pasta config. Vamos fazer assim padronizar o código e encapsular as funções.

**Comment by m4rllon** [comment]
Ok!
