### ISSUE TITLE
Bugs do Deploy do Site

### ISSUE THREAD

**Issue by MariaCHelena** [unb-mds/LicitaBSB-24.1#132]
**Descrição/Objetivo:**
Issue destinada a documentar e organizar os bugs que forem sendo identificados no deploy do site.

**Tarefas:**
- [x] Documentar os bugs nos comentários da Issue.
- [x] Bug deve possuir foto e descrição, e critérios de aceitação.

**Critérios de aceitação:**
- [x] Todos os bugs encontrados foram corrigidos

Link do site: [link](https://fastidious-daffodil-724e94.netlify.app/)

**Comment by nateejpg** [comment]
Existe um pequeno bug na renderização de algumas imagens no Deploy. Meu palpite é que seja o path dos arquivos nos diretórios, quando saem do modo produção para o produto final. 
![image](https://github.com/user-attachments/assets/bb642ae3-9b7c-4a00-9c35-9a4985d126ab)

**Comment by nateejpg** [comment]
Quando estamos navegando pelas licitações, ele disponibliza até 35578, porém ao clicar leva para um endpoint sem nada, testei com 10 unidades antes e ainda está com o endpoint vazio. Deve ter algum objeto quebrado.

![image](https://github.com/user-attachments/assets/5f8d5762-7c22-4726-85a1-c47680faf6f5)

**Comment by moonshinerd** [comment]
Meu palpite a esse segundo report é que esteja acontecendo pela aplicação não está sabendo lidar com algumas tags vindo como null para o final.

**Comment by thaleseuflauzino** [comment]
> Existe um pequeno bug na renderização de algumas imagens no Deploy. Meu palpite é que seja o path dos arquivos nos diretórios, quando saem do modo produção para o produto final. ![image](https://private-user-images.githubusercontent.com/91135190/356825711-bb642ae3-9b7c-4a00-9c35-9a4985d126ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzOTYyNDAsIm5iZiI6MTcyMzM5NTk0MCwicGF0aCI6Ii85MTEzNTE5MC8zNTY4MjU3MTEtYmI2NDJhZTMtOWI3Yy00YTAwLTljMzUtOWE0OTg1ZDEyNmFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODExVDE3MDU0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhOGIzYjQ2MWFkMDYzMmNhZTgxM2Q3YWM3OWU0Y2FkZjhiMmNmYmEwOTc2ZDdhNjU0YWQ5NGUzNjVkMTBjZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.92-Mts1H_95c1nQk6icOO542w3arlr-B0_a8QiSIvNI)

Resolvido pelo @moonshinerd

**Comment by thaleseuflauzino** [comment]
Em todas as licitações de extratos há dois "R$"

![Imagem do WhatsApp de 2024-08-10 à(s) 00 53 04_5c996c4a](https://github.com/user-attachments/assets/6ae4018e-852c-4990-85ab-4b62c0de10f0)

**Comment by moonshinerd** [comment]
> > Existe um pequeno bug na renderização de algumas imagens no Deploy. Meu palpite é que seja o path dos arquivos nos diretórios, quando saem do modo produção para o produto final. ![image](https://private-user-images.githubusercontent.com/91135190/356825711-bb642ae3-9b7c-4a00-9c35-9a4985d126ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzOTYyNDAsIm5iZiI6MTcyMzM5NTk0MCwicGF0aCI6Ii85MTEzNTE5MC8zNTY4MjU3MTEtYmI2NDJhZTMtOWI3Yy00YTAwLTljMzUtOWE0OTg1ZDEyNmFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODExVDE3MDU0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhOGIzYjQ2MWFkMDYzMmNhZTgxM2Q3YWM3OWU0Y2FkZjhiMmNmYmEwOTc2ZDdhNjU0YWQ5NGUzNjVkMTBjZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.92-Mts1H_95c1nQk6icOO542w3arlr-B0_a8QiSIvNI)
> 
> Resolvido pelo @moonshinerd


**Comentário Complementar:**

A correção foi realizada ajustando a lógica de resolução dos caminhos das imagens no processo de build. O problema estava relacionado ao path dos arquivos que, durante o build, não eram corretamente referenciados no produto final. 

Foi necessário garantir que os caminhos das imagens fossem resolvidos de forma dinâmica, de acordo com o ambiente de produção, utilizando uma abordagem que assegure que o path correto seja gerado durante o processo de build. Esse ajuste resolveu o problema, garantindo que as imagens fossem renderizadas corretamente após o deploy.

**Comment by thaleseuflauzino** [comment]
> Em todas as licitações de extratos há dois "R$"
> 
> ![Imagem do WhatsApp de 2024-08-10 à(s) 00 53 04_5c996c4a](https://private-user-images.githubusercontent.com/120137721/356894790-6ae4018e-852c-4990-85ab-4b62c0de10f0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzOTc0MTgsIm5iZiI6MTcyMzM5NzExOCwicGF0aCI6Ii8xMjAxMzc3MjEvMzU2ODk0NzkwLTZhZTQwMThlLTg1MmMtNDk5MC04NWFiLTRiNjJjMGRlMTBmMC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMVQxNzI1MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MjgxODFmZWFmNGU3ZjM3NTEwZmFiN2M4ODA1NmI0MTIyN2RkOWM0M2E4MjQwODdjMzllNWE5OTFhODMwZWUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8ROGS4I4SO-xJXpsA4KtStZyLfK_F3fjoICOwFZYV2k)

Resolvido por mim no commit [5f47e21](https://github.com/unb-mds/LicitaBSB-24.1/commit/dee938281e0a9d0af0b153f913b90876b8d0405b)

**Comment by thaleseuflauzino** [comment]
O link e logo do "Github" não está padronizado nem a cor e nem a posição

![image](https://github.com/user-attachments/assets/f0f5af56-c089-4cd5-afb1-b62b082ccdbd)

**Comment by thaleseuflauzino** [comment]
> O link e logo do "Github" não está padronizado nem a cor e nem a posição
> 
> ![image](https://private-user-images.githubusercontent.com/120137721/356895773-f0f5af56-c089-4cd5-afb1-b62b082ccdbd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzOTkzNDIsIm5iZiI6MTcyMzM5OTA0MiwicGF0aCI6Ii8xMjAxMzc3MjEvMzU2ODk1NzczLWYwZjVhZjU2LWMwODktNGNkNS1hZmIxLWI2MmIwODJjY2RiZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMVQxNzU3MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZmI0YzExMWFhYjYwMjlmOTE4NjYxOTA3ZmVkMzNhNDhhODRlZDk0NGFlNmY1MmFhNzlhNDYxNDgwODdmZjRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FYiFNOs1QEbH-Lx73qF26ZZ_KdVsELYncCzDfIf1Jzc)

resolvido nos commits: [39c163c](https://github.com/unb-mds/LicitaBSB-24.1/commit/39c164c1992b4e3f0b4a98dd6bbe1849ec957191) e [6ebd4e1](https://github.com/unb-mds/LicitaBSB-24.1/commit/6ebd4e138fcbe232158efd05538b757e2f51b74a)

**Comment by moonshinerd** [comment]
A responsividade do site pra mobile não está funcionando, fica tudo bugado. Aqui abaixo a homepage. 
![Screenshot_20240811-173919_Chrome.jpg](https://github.com/user-attachments/assets/7ff7cdd5-cc0e-493f-a957-e4cef8eadf6d)

A página sobre nós tbm se encontra com o mesmo problema porém só com uma barra no lado direito que desorganiza tudo. O mesmo acontece na página de licitações

**Comment by moonshinerd** [comment]
Todos os bugs reportados nessa issue foram consertados e reparados
