### ISSUE TITLE
Popular banco de dados

### ISSUE THREAD

**Issue by MariaCHelena** [unb-mds/LicitaBSB-24.1#62]
**Descrição/Objetivo:**
Nessa issue o nosso banco de dados deverá ser populado com as informações das licitações obtidas. Essas licitações deverão possuir os seguintes padrões:
- Número Licitação
- Nome UG
- Modalidade de Compra
- Número do Processo
- Objeto
- Situação Licitação
- Nome Órgão Superior
- Nome Órgão
- UF/Município
- Data Resultado Compra
- Data Abertura
- Valor Licitação

**Tarefas:**
- [x] Formatar todos os dados para possuírem o mesmo padrão descrito acima;
- [x] Popular o banco de dados com os dados do portal da transparência;
- [x] Adicionar novas licitações extraídas do Diário Oficial.

**Comment by moonshinerd** [comment]
Issue finalizada, @thaleseuflauzino padronizou e criou um json global que se encontra no diretorio `backend/data_collection/database/data.json`.
